package-lock.json, package.json
Adds jest config necessary to run both js and ts tests at the same time from the top-level directory snapp-cli directory.
Fixes o1-labs/snapp-cli/issues/30.
=> Add jest config in package.json to capture both js/ts files, transform ts

src/postinstall.js
When running npm v6, npm will give an error if you give multiple dependencies to the `npm cache add` command. 
Instead of adding all dependencies in one line, we can iterate through the list of dependencies and add them one by one in an async operation.
=> fix: Iterate through npm cache dependencies

package-lock.json, package.json, templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/tsconfig.json
so Node 12 doesn't warn when running tests
=> fix: change project template's tsconfig.json target to ES2019 

package-lock.json, package.json, src/lib/example.js, src/lib/file.js, src/lib/project.js, src/lib/project.test.js, src/postinstall.js
Fixes https://github.com/o1-labs/snapp-cli/issues/62 and https://github.com/o1-labs/snapp-cli/issues/63
**Description**:
This addresses the issue on Windows when creating a new project or example. A lot of the paths used throughout the project references paths that are not compatible with windows. To address this, `path.join` was used to concatenate paths together.  There is an additional fix with the `git commit` command where it seems to require double quotes on Windows. 
**Tested By**
Tested by running through a manual test with `npm link`. The resulting output has successful steps for both initializing a git repo and setting it up.
```
λ snapp project bar2
√ Fetch project template
√ Initialize Git repo
√ NPM install
√ Set project name
- Git init commit...warning: LF will be replaced …
```
=> feat: Add Windows support for project and example

src/lib/system.js, templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/src/index.ts, templates/project-ts/tsconfig.json
This PR adds SnarkyJS to the project as an NPM dependency. Users will now be able to create a project and have Snarky available right away and start building. 
**Changes**
- Adds SnarkyJS to package.json
- Changes tsconfig.json to support SnarkyJS
**Left to do**
This PR has not implemented Jest tests to work yet. This has been a challenge with Jests runtime expects packages from node_modules to be in CJS format and if they are not, it tries to transform them on runtime. Both these approaches have been causing issues and in the spirit of unblocking others on this change, I will follow up on adding Jest in another PR.
=> Add SnarkyJS to project 

examples/tictactoe/ts/src/index.ts
This adds the tictactoe example to snapp-CLI.
I can't test if this works locally (via `./src/bin/index.js example tictactoe`) because `example.js` uses `github:o1-labs/snapp-cli#main` as source for the examples. I'm guessing it does that because the installed snapp does not have access to its own source. Perhaps we could whitelist the `examples/` folder via files in `package.json`?
=> adding tictactoe example

src/lib/example.js
see https://github.com/lukeed/gittar#optionsforce
> Force a HTTPS download. If there is an error with the network request, a local/cache lookup will follow.
=> fetch examples all the time, fallback on local

src/bin/index.js
**Description**:
When using an unknown command, `strict()` will catch the command being wrong but when specifying a wrong command with an option, yargs will throw an error related to https://github.com/o1-labs/snapp-cli/issues/77
To fix this, we remove the `strict()` option and add `strictCommands()` and `strictOptions()`. `strictCommands()` is similar to `strict()` that it applies to unrecognized commands but we also add `strictOptions()` to catch unrecognized options as well. This makes the `snapp-cli` not throw an error when an invalid argument and an invalid option are passed together. 
**Tested**
Manually tested by specifying wrong commands and options.
**Output**
```
$ snapp-cli foo
Usage: snapp <command> [options]
Commands:
snapp project [name]  Create a new project …
```
=> Fix error thrown by yargs on invalid argument and option

src/lib/file.test.js
Instead of using a manually specified Windows path, replace that logic with `path.join`. This is a cleaner way to do things and doesn't require checking for a Windows environment since `path.join` handles that already.
**Tested**
By running the unit tests for `snapp-cli`
=> Use path.join instead of manually checking for Windows path

templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/src/index.test.ts, templates/project-ts/src/index.ts
Add an example contract that adds the Field elements 1 + 2.
**Note**
The test file in the `templates/project-ts` has not been updated as it depends on https://github.com/o1-labs/snapp-cli/pull/100 to land. Tests can be added in a follow-up PR.
**Tested**
Ran `npm run build` and builds successfully
Ran `node build/src/index.js` no errors are shown
=> Add example contract that adds 1 + 2

.github/workflows/ci.yml, package-lock.json, package.json, runTests.sh, templates/project-ts/babel.config.cjs, templates/project-ts/jest.config.js, templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/resolver.cjs, templates/project-ts/src/index.test.ts
This adds the necessary Jest configurations to allow running SnarkyJS in the Jest runtime environment. 
Firstly, we specify Jest to use the experimental support for ESM modules by using the `-experimental-vm-module` flag and using the `ts-jest/presets/default-esm` preset. 
Secondly, we add a new babel config to transpile any ESM `node_modules` dependencies used in SnarkyJS. If we do not transpile the ESM dependencies for SnarkyJS, Jest will throw an error on runtime. The specific dependency that causes issues is the `tslib` package. We continue to use the `ts-jest` transformer for the TypeScript files.
Thirdly, we create a `resolver.cjs` file to specifically import the Node ESM version of SnarkyJS. Since the `exports.default` property is set to the web version in the …
=> Add Jest configs for SnarkyJS

package.json
Without specifying the eslint config to use, eslint looks for all configs (including the child project) and consequently complains about missing the snarkyjs custom eslint plugin. Specifying which eslint config to use fixes this.
=> fix: use root eslint config

templates/project-ts/src/index.ts
Removes the `default export` statement from the template Smart Contract. This is non-idiomatic as we expect Smart Contracts to be exported using named exports instead.
=> fix: Switch to using named export instead of default export

src/lib/config.js, src/lib/deploy.js, src/lib/example.js, src/lib/file.js, src/lib/helpers.js, src/lib/project.js
This should fix all problems with `zk deploy`.
* To avoid complications with two instances of snarkyjs, we import snarkyjs from the user directory:
```js
let snarkyjs = await import(`${DIR}/node_modules/snarkyjs/dist/server/index.mjs`);
```
* To avoid another dependency that has to be kept up to date, we sign the transaction with snarkyjs instead of mina-signer. Thus, `zk deploy` _only_ depends on libraries present in the user directory. This enables us to deploy zkapps in up to date user projects even with an older version of the zkapp cli, provided that the snarkyjs APIs we use for deploying remain stable.
* To circumvent issues with the existing snarkyjs `deploy()` command, which lead to a wrong nonce & other stuff, we construct the deploy transaction directly with `Mina.transaction`. …
=> Fix deploy command

examples/sudoku/ts/src/index.ts, examples/sudoku/ts/src/sudoku-zkapp.ts, examples/tictactoe/ts/src/index.ts, package-lock.json, package.json, templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/src/index.ts
**Description**:
1. Update `snarkyjs` to `0.3.3`
2. Update examples to use new APIs that are exposed by `snarkyjs`
3. Remove any references of `snapp` and replace with `zkApp`
**Tested By**:
Manually testing. Built the new examples and ran them as normal. Compared output with previous iterations to confirm the same behavior.
=> Update examples to use new APIs and remove `snapp` references

package-lock.json, package.json, src/lib/config.js, src/lib/deploy.js
Adding the fee step when running `zk deploy` broke the non-interactive workflow. To fix this, we ask the user to specify a default amount in their `config.json`. When running the deploy non-interactively, the CLI will look inside `config.json` to use the specified fee amount.
**Tested By**
Running `npm link` and then manual testing.
=> Add configurable fee amount to config and deploy to reenable non-interactivity

package-lock.json, package.json, src/lib/deploy.js
This PR handles several different UX issues.
1. If there was an error submitting a deploy mutation, there was inconsistent error handling which made it so that it would show a success message with an undefined deploy hash value. This has been fixed by fixing the error handling case when submitting the mutation.
2. If the user tries to deploy their zkApp without their account being funded, it will not be in the ledger and fetching account info will fail. This has been fixed by providing better error messages to indicate what failed and how the user can fix it.
3. If the user specifies an invalid nonce value, show a better error message as a failure reason.
Related to this Discord discussion: https://discordapp.com/channels/484437221055922177/915745847692636181/97617883628477 …
=> feat(deploy): Add better error handling when deploy fails

package-lock.json, package.json, src/lib/deploy.js
Check the specified URL for the node status before deploying. If the node is completely offline or gives a bad response, we return early. If the node is in either `CONNECTING`, `BOOTSTRAP`, or `CATCHUP`, we also report an error and return early.
**Tested By**
Manual testing.
=> Query node status and report if not stable

src/lib/deploy.js
Removes the nonce request from the user when the cli cannot find the specified account information. It was noted that asking for a manual nonce value doesn't really make sense in the situation since if we cannot find the account information on the network, deploying with the same endpoint probably won't work. 
To make the code simpler in the cli, we can remove this check and always assume we will get the account information from the specified network graphql endpoint.
=> Remove manual nonce request from user

examples/tictactoe/ts/src/index.ts, examples/tictactoe/ts/src/tictactoe-lib.ts, examples/tictactoe/ts/src/tictactoe.test.ts, examples/tictactoe/ts/src/tictactoe.ts
This PR adds two different things for the `TicTacToe` example.
Firstly, it adds tests for the `TicTacToe` smart contract.
Secondly, applied some refactoring to make the smart contract more unit testable.
Separated out some common helper functions into `tictactoe-lib.ts` to make the functionality easier to test. Refactored `index.ts` to use these helper functions to make things shorter and easier to read. 
Additionally made the `deploy` function on the `TicTacToe` example not set any state and instead used an `init` method to do that. [See reasoning here.](https://github.com/o1-labs/zkapp-cli/pull/198#discussion_r885330941)
If users still want to run the example, they run `npm run build && node build/src/index.js`
**Tested By**
Running unit tests and deployed to Berkeley
=> Add Tests to tictactoe example

templates/project-ts/src/index.test.ts, templates/project-ts/src/index.ts
This PR adds better unit tests to the template zkapp project. It scaffolds using the local ledger and simulates updating the state in the local ledger. This will give users a much better starting point when they are messing around with the API.
This was also additionally done to make writing documentation for testing easier. As I was writing docs for methods for testing your smart contract, it felt weird that this sort of code wasn't already included.
**Tested By**
Updating and running the unit tests
=> Update tests to use local ledger and setting state in template project

package-lock.json, package.json, src/lib/deploy.js, templates/project-ts/package-lock.json, templates/project-ts/package.json
this updates snarkyjs and typescript, fixes the deploy command, and tweaks the error output when the graphql endpoint returns an error, to show the actual output instead of demanding to "try again"
=> Update snarkyjs & deploy

.github/workflows/ci.yml
The `node_modules` for the template zkApp was being included in the build for our npm package. This makes our unpacked size `206 MB` at the moment! https://www.npmjs.com/package/zkapp-cli/v/0.3.7
After running the tests in CI, we delete the node_modules manually
=> Remove node_modules from examples/templates

package.json, templates/project-ts/package.json
Fixes #222
Add SnarkyJS as a peer dependency on CLI project and example templates. 
Tested
Used this version of the CLI to successfully create new template and example projects that have SnarkyJS as a peer dependency.
=> Add SnarkyJS as a peer dependency in project and example templates

templates/project-ts/tsconfig.json
Addresses #228 
Adds a tsconfig option to avoid errors when not using a constructor on classes that extends CircuitValue.
=> Update tsconfig to allow extending CircuitValue without a constructor

examples/sudoku/ts/src/sudoku.ts, examples/tictactoe/ts/src/run.ts, examples/tictactoe/ts/src/tictactoe.ts, package-lock.json, package.json, templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/src/Add.ts
**Description** 
Addresses #227 & #229
This PR adds preconditions to the template and example contracts that links accessing contract state via `.get` to actual on-chain state. A static `from` method was also added to the sudoku smart contract to invoke the original constructor instead of overriding it. This is a necessary refactor after the new SnarkyJS CircuitValue improvements. See [this discussion](https://github.com/o1-labs/snarkyjs/pull/269) for more details.
=> Update template and examples with preconditions and new CircuitValue improvements [Do Not Merge Until New Published Version of SnarkyJS is Added] 

package.json, src/lib/deploy.js
=> Fix deploying to QANet with zk deploy command

CHANGELOG.md, examples/sudoku/ts/src/sudoku.ts, examples/tictactoe/ts/src/run.ts, examples/tictactoe/ts/src/tictactoe-lib.ts, package-lock.json, package.json, src/lib/deploy.js, templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/src/Add.test.ts
Addresses 
#248 
This PR renames all references of party to accountUpdate, and parties to zkappCommand. Fixes were also made to make the CLI compatible with SnarkyJS 0.6.0. The CLI version was bumped to 0.4.15. 
Renames
-CLI: graphql mutations
-Template: tests
-Examples: tests/lib
Fixes
-CLI : snarkyJS local file path
-Template/Examples: tests
**Tested**
The CLI was used to generate, run and deploy example projects. A project was successfully deployed to QAnet here https://berkeley.minaexplorer.com/transaction/CkpZToB1KNYg5M79bivvE557BP1W8e9p7vp1WZCVycJ3yHmS4noo5 .
=> Rename references to party and bump SnarkyJS to 0.6.0

src/lib/helpers.js, src/lib/project.js
This way it is not automatically consumed by the next step, such as the yes/no confirmation step.
Fixes https://github.com/o1-labs/zkapp-cli/issues/194 
Tested on deployment. Works. The Ora steps aren't messed up if typing during them, and the input isn't invisibly passed to the yes/no prompt, as was the case previously. Now it will show all the junk text, if a user entered any, allowing them to clear it out and proceed in a predictable manner.
=> Make Ora discard stdin

src/bin/index.js
Example error output if user uses an invalid example name:
> ❯ zk example foo
> zk example [name]
> 
> Create an example project
> 
> Options:
>       --name  [string] [required] [choices: "sudoku", "tictactoe"]
>   -h, --help     Show help                               [boolean]
>   -v, --version  Show version number                     [boolean]
> 
> Invalid values:
>   name was "foo". Must be one of: "sudoku", "tictactoe".
(We don't have a lot of flexibility in the formatting of that error message because it must accept three string replacements. But I made it more readable than the default error message provided by yargs.)
=> Constrain examples names to valid names

.github/ISSUE_TEMPLATE/config.yml
hopefully this works. The escaping character is displayed as a literal, for some reason.
=> Remove escaping on # on issue template

src/bin/index.js, src/lib/helpers.js, src/lib/project.js, src/lib/project.test.js
Adds ability for a dev to create a UI project that lives alongside their smart contract, in the same directory and git repo.
A dev can do this by providing a `--ui` arg to the `zk project <name>` command:
```
zk project foo --ui svelte     // SvelteKit
zk project foo --ui next       // NextJS
zk project foo --ui vue        // VueJS
zk project foo --ui empty      // empty ui directory
zk project foo --ui none       // no ui directory; only the smart contract (similar to old behavior of `zk project foo`)
zk project foo --ui unsupported // example invalid value; shows an error and tells user to choose one of the supported choices a, b, c.
```
This also allow this method to be called non-interactively inside a shell script.
If no parameter is provided, a dropdown is shown:
```
❯ zk project …
```
=> Working mvp of UI monorepo

src/lib/project.js
Fixes #272 
The CLI now exits when there is a failure in any step during project creation.  We can wait to bump the CLI version until we finish the remaining tasks surrounding the UI scaffold features.
=> Exit the CLI when a project step fails

src/lib/project.js
Closes https://github.com/o1-labs/zkapp-cli/issues/280
To discuss: if we should use `0.*` or `0.6.*` as the version. The latter takes more work to maintain manually or code to get working to stay in sync with the contracts project dir, which isn't yet created at this point in the script.
=> feat: add SnarkyJS to the ui project package.json dependencies

templates/project-ts/tsconfig.json
This changes the TS `target` from `es2019` to `es2020`, to get bigint literal syntax
It also sets `sourceMap: true` for better debugging
=> Update ES target

package-lock.json, package.json, src/lib/deploy.js
Addresses #255 when a deployment fails with an error response that is not in the form we expect. When a GraphQL error occurs, we expect an array of errors to be returned from the endpoint we are issuing. When an error returns that's not an array, an unhelpful message is shown along the lines of:
```sh
zk deploy 
✔ Build project
✔ Generate build.json
✔ Choose smart contract
The 'Square' smart contract will be used
for this network as specified in config.json.
✔ Generate verification key (takes 10-30 sec)
Using the cached verification key
✔ Build transaction
✔ Send to network
zk deploy [alias]
Deploy or redeploy a zkApp
Options:
-y, --yes      Respond `yes` to all confirmation prompts.
Allows running non-interactively within a script.     [boolean]
-h, --help     Show help …
```
=> Provide a better error message when an unknown error occurs in deployment

examples/sudoku/ts/src/sudoku.ts, examples/tictactoe/ts/src/tictactoe-lib.ts, package-lock.json, package.json, templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/src/Add.test.ts, templates/project-ts/src/Add.ts
For Berkeley redeployment. 
Still needs `npm install` run in this project's root directory and `project-ts` directory, and to commit `package-lock.json`. it's not possible to do that successfully until SnarkyJS is available on NPM at `0.7.0`.
=> Bump version of zkapp-cli to 0.5.0 and snarkyjs to 0.7.0

.eslintrc.js, examples/sudoku/ts/src/run.ts, examples/sudoku/ts/src/sudoku-lib.js, examples/sudoku/ts/src/sudoku.test.ts, examples/sudoku/ts/src/sudoku.ts, src/lib/deploy.js, templates/project-ts/.eslintrc.cjs, tsconfig.json
This PR
- fixes the sudoku example
- does a fairly large refactor of the sudoku example, so that it doesn't rely on `this.sign()`, uses Struct instead of CircuitValue, uses snarkyjs APIs directly instead of custom helper functions, and makes `run.ts` script use proofs (the tests use `proofsEnabled: false`)
- during deployment, checks if the smart contract has `init()` decorated with `@method`. If yes, then we have to create a proof to deploy successfully; this is done in a separate step that's shown to the user, after building the transaction
Other small changes:
- Add TS config at the top level so we have proper type feedback in the examples
- Tweak eslint config to not show an error for the sudoku code
=> Fix Sudoku and enable CLI to create init() proofs

package-lock.json, package.json, src/lib/deploy.js, templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/src/Add.test.ts, templates/project-ts/src/Add.ts, templates/project-ts/src/interact.ts
- refactors the Add contract similarly to [Sudoku](https://github.com/o1-labs/zkapp-cli/pull/315)
- fixes the way `zk deploy` gets the current account, so that it can determine whether to call `init()` correctly
- adds a script `interact.ts` which can be invoked by users after deploying their contract, with detailed comments
- bumps release
TODOs:
- https://berkeley.minaexplorer.com/wallet/B62qrDe16LotjQhPRMwG12xZ8Yf5ES8ehNzZ25toJV28tE9FmeGq23A
=> Fix Add, add interaction script and release 0.5.3

package-lock.json, package.json, src/lib/file.js, templates/project-ts/tsconfig.json, tsconfig.json
this PR makes two changes which are a frequent source of errors when building fresh projects, and in particular, currently break at least two of the tutorials
* remove the `isolatedModules` flag from the TS config. this flag frequently causes errors about not being able to compile files without import/exports (e.g., as created by the `zk file` command). I don't see benefits of having this flag on which would make up for that
* change the `zk file` command, to not add an import in the test file like `import Contract from './Contract'`
* since the `Contract.ts` file is initially empty, the test file is initially wrong and can't be built
* also, it assumes that the smart contract is exported as default, while all our examples export it as a named export
* so I commented the line out in the …
=> Fix build errors after `zk file`

src/lib/project.js
Issue: Terminal console logging is stuck after creating a new project via command `zk project <newProject>`
Change: Added `process.exit(0)` so that the process exits without having the user terminating manually.  
CLI output: 
```bash
Next steps:
cd testapp1
git remote add origin <your-repo-url>
git push -u origin main  # process should exit properly here
```
=> Fix hung CLI after creating new project

templates/project-ts/jest.config.js
It seems the jest tests fail if you use `.js` in the file path names. Conversely, `npm run start` fails if you don't have `.js` in the filename
To solve this problem, I make that Jest maps imports that end in `.js` to ones that don't. Seems to fix the issue
https://stackoverflow.com/a/69598249/1780045
=> Fix "cannot find module" when running jest tests

src/bin/index.js, src/lib/example.js
Closes #168 
This PR adds a dropdown to select an example project when `zk example` is entered in the CLI without entering an example name.
=> Add dropdown to select an example project

CHANGELOG.md, package.json, src/lib/system.js
Fixes #345 
**Background**
When the `zk system` command is entered, the installed SnarkyJS version is not shown along with the other system info. 
```
System:
OS: macOS 12.0.1
CPU: (10) arm64 Apple M1 Pro
Binaries:
Node: 18.3.0 - /opt/homebrew/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 8.11.0 - /opt/homebrew/bin/npm
npmPackages:
snarkyjs: Not Found (not in a project)
npmGlobalPackages:
zkapp-cli: 0.5.4
```
This occurs because SnarkyJS is a peer dependency of zkApp projects, and the library used to get system info is not able to find peer dependency packages.  This PR adds functionality to get the users SnarkyJS version and display it along with the other system info.
=> Show SnarkyJS version with zk system

package.json, src/lib/deploy.js
Fixes #352 
**Issue** 
When entering the command `zk deploy` an error is issued from `deploy.js` which stops the cli from continuing. This occurred because the `npm list --location=global` command used to get the users current installed zkapp-cli version does not work correctly on older versions of node. The command was switched to use the legacy `npm list -g` command. This fix was tested with both Node 16 and 18.
=> Fix zk deploy

examples/sudoku/ts/src/run.ts, examples/sudoku/ts/src/sudoku.test.ts, examples/tictactoe/ts/src/run.ts, examples/tictactoe/ts/src/tictactoe.test.ts, package-lock.json, package.json, src/lib/deploy.js, templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/src/Add.test.ts, templates/project-ts/src/interact.ts
Addresses #334 & #337
This PR updates the CLI to be compatible with the upcoming SnarkyJS 0.8.0 release. The `Mina.transaction` api has been updated to pass in the fee payer as a public key throughout the CLI and in all the example and template contracts. See [this](https://github.com/o1-labs/snarkyjs/pull/652) SnarkyJS PR and this [issue](https://github.com/o1-labs/snarkyjs/issues/635) for more details.
=> Update to SnarkyJS 0.8.0 [Do Not Merge Until SnarkyJS 0.8.0 is Published to npm and Added]

CHANGELOG.md, package.json, src/lib/config.js, src/lib/deploy.js
Closes #357
This PR displays the developers desired blockchain explorer URL after sending a deploy transaction. 
**Approach**
The desired blockchain explorer name is parsed from the `Mina GraphQL API URL` that the developer adds after entering the `zk config` command. A blockchain explorer URL with a transaction hash, is constructed and displayed in the `zkapp-cli` after sending a deploy transaction.  This can be extended to support Mainnet and future blockchain explorers. 
The blockchain explorer name is also added to the displayed faucet URL as a query parameter after a developer enters the `zk config` command and adds a new `Mina GraphQL API URL`. The explorer name query parameter can be used in the faucet to display the desired block explorer transaction URL after an account is …
=> Show desired block explorer urls 

src/lib/config.js, src/lib/deploy.js, src/lib/deploy.test.js, templates/project-ts/config.json
Closes #217 
This PR updates `networks`  to `deployAliases` in the `config.json` and throughout the `zkApp-cli` for clarity. The `config.js` and `deploy.js` files were changed to support both cases if either `networks` or `deployAliases` are found in the `config.json`.
=> Update "networks" in config.json to "deployAliases" 

package-lock.json, package.json, src/postinstall.js
Closes #314 
**Background**
Sometimes the installation or upgrade of the zkapp-cli hangs during the `warm cache for project template` step in the `postinstall.js` file when a network request is made by gittar to fetch the zkapp-cli templates and examples from github [here](https://github.com/o1-labs/zkapp-cli/blob/main/src/postinstall.js#L59).
**Approach**
This PR adds a timeout to the fetch gittar operation. If the fetch operation does not resolve before the the timeout, the `warm cache for project template` step is skipped, and the installation continues. See [this](https://github.com/o1-labs/zkapp-cli/issues/314) discussion for more details. 
**Next steps**
A log was added to show which NPM packages were added to the cache in the `warm NPM cache for project template deps` step. A log …
=> Add timeout to warm gittar cache step

templates/project-ts/.eslintrc.cjs
this fixes the problem that eslint is not able to properly parse TS files, it has problems like complaining when types for function signatures "don't use their function arguments".
source for solution: https://stackoverflow.com/a/58513127/7354533
I think there would be an alternative to this: not use `@typescript-eslint/parser` at all. in that case, type linting is done by TS itself, that's how it is setup in the snarkyjs repo and seems to work very well.
=> Improve eslint config for typescript

package-lock.json, package.json, src/lib/project.js, src/lib/ui/next/customNextIndex.js
**Description** 
fixes #372 
**Background**
The UI scaffold fails when a user runs `zk project someproj --ui next` and selects yes when prompted to add a src directory. 
```
Would you like to use `src/` directory with this project? … No / Yes
```
This option was recently added to `create-next-app`. The error occurred because the scaffold expects a pages directory at the root of the UI project. 
**Solution** 
This was resolved by passing a flag to `create-next-app` to add a src directory as a [default](https://nextjs.org/docs/advanced-features/src-directory). The `pages` paths in the scaffold were updated to include src as well as the contract imports.
=> Fix NextJS UI scaffold

package-lock.json, package.json, src/bin/index.js, src/lib/project.js
Description
fixes #380 #381  
**Background**
The ui scaffolding fails for NextJS if you check yes for `Do you want to setup your project for deployment to Github Pages?`. This was blocking people from completing tutorial 4.
**Solution**
This was resolved by updating the the ui file paths in the scaffold when the option to deploy to github pages is selected. 
An interactive flow was also added as a default to guide a user to add an accompanying ui project after entering `zk project <project-name>`. 
```
? Create an accompanying UI project too? …
❯ next
svelte
nuxt
empty
none
```
=>  Add UI scaffold interactive flow and fix NextJS Github Pages scaffold

package-lock.json, package.json, src/lib/project.js, src/lib/ui/next/customNextIndex.js
Description
This PR updates the `zkapp-cli`  with minor changes and bumps the cli version.
- Update the get started file path on the next landing page 
- Remove the possibility of prompting the user twice if they want to generate a typescript project.
=> Update UI scaffolds and bump cli to 0.7.6

src/bin/index.js
As I begin my work with the zkApp CLI, I am seeing opportunities to improve the CLI help wording.
Less friction = more success
=> fix: update file CLI help text

examples/sudoku/ts/src/run.ts, examples/sudoku/ts/src/sudoku.test.ts, examples/sudoku/ts/src/sudoku.ts, examples/tictactoe/ts/src/run.ts, examples/tictactoe/ts/src/tictactoe.test.ts, examples/tictactoe/ts/src/tictactoe.ts, package-lock.json, package.json, src/lib/deploy.js, src/lib/example.js, src/lib/file.test.js, src/lib/project.js, src/lib/system.test.js, src/lib/ui/next/customNextIndex.js, src/lib/ui/nuxt/customNuxtIndex.js, src/lib/ui/nuxt/headers.js, templates/project-ts/jest.config.js, templates/project-ts/package.json, templates/project-ts/src/Add.test.ts, templates/project-ts/src/Add.ts, templates/project-ts/src/interact.ts
This PR is the corresponding zkApp cli  release to [this](https://github.com/o1-labs/snarkyjs/pull/872) SnarkyJS PR release of version `0.10.0`.
- SnarkyJS minor version dependency updated in cli package.json to `0.10.*`.
- SnarkyJS minor version peer dependency updated in template/example contract package.json to `0.10.*`.
- Remove deprecated `isReady` and `shutdown` from cli, template/examples contracts, and UI scaffolds for each supported framework. 
- Configure UI scaffolds for `NextJS`, `Svelte,` and `Nuxt` to support top-level await used in the latest SnarkyJS release.
- Exit the cli config and deploy processes on success and error.
- Add `state.getAndAssertEquals()` to examples and test contracts. 
- Increase the template/example project jest test timeout.
**Tested**
This was …
=> CLI Release 0.8.0

package-lock.json, package.json, src/lib/project.js
Fixes #401 
The cli ui scaffold currently does not support using the new NextJs [App Router](https://nextjs.org/docs/app). The scaffold fails if a user selects yes to the prompt to use the App Router. 
This PR adds a flag to select no to using the App Router as a default. The `create-next-app` version is also locked to the current version `13.4.1` to avoid  future breaking changes to the scaffold. A [seperate issue](https://github.com/o1-labs/zkapp-cli/issues/400) was created to add support to use the App Router.
=> Update Next UI scaffold defaults

package-lock.json, package.json, src/lib/deploy.js, src/lib/helpers.js
fixes https://github.com/o1-labs/zkapp-cli/issues/406
* no longer use the `zkAppKey` argument of `deploy`, which was just a workaround for a missing precondition
* a [snarkyjs PR](https://github.com/o1-labs/snarkyjs/pull/908) will remove this argument from snarkyjs, but we can stop using it independently
* remove other manual patching of `zkapp.deploy()` that is no longer necessary
* log full error trace to the console, so debugging CLI failures becomes less painful:
=> Clean up deploy and log full errors to the console

templates/project-ts/src/interact.ts
Very small PR renaming the `network` arg to `deployAlias` in the interact template since that's technically what it is.
=> Rename network to deployAlias

CHANGELOG.md, examples/sudoku/ts/src/sudoku.ts, examples/tictactoe/ts/src/tictactoe.ts, package-lock.json, package.json, templates/project-ts/package.json
Closes #425 
This PR is the corresponding zkApp cli release to the SnarkyJS release of [version 0.11.0](https://github.com/o1-labs/snarkyjs/pull/938/).
- SnarkyJS minor version dependency updated in cli package.json to 0.11.*.
- SnarkyJS minor version peer dependency updated in template/example contract package.json to 0.11.*.
- Replace deprecated `Circuit.if` with `Provable.if` in the `tictactoe` example.
- Replace deprecated `Circuit.array` with `Provable.Array` in the `sudoku` example.
**Tested**
This was tested by generating projects with various cli flows. The template [add](https://berkeley.minaexplorer.com/transaction/5JuTv2pbkwpyZyJ739xEoc9uxAnbe3MMGUmZVnwthr6WM9wwPPX3) contract, [sudoku](https://berkeley.minaexplorer.com/transaction/5JuLmfBCHsyLERT49MAWoBsyw8nqpWxsRZPsXCM2nhsqYq4z …
=> CLI Release 0.9.0

package-lock.json, package.json, src/lib/config.js, src/lib/deploy.js, src/lib/helpers.js, src/lib/prompts.js, templates/project-ts/src/interact.ts
closes #129 #429 #435 
Currently, the zkApp cli creates a keypair for the zkApp account after running the `zk config` command.  The cli assumes that this zkApp account has funds to pay fees, and uses it as fee payer. 
There are two reasons why the flow above is insufficient:
**Incompatible with permissions**  
- A zkApp is deployed with `send: proof` permissions by default which means you need to provide a proof (of running a smart contract method) as authorization to send MINA away from the zkApp account. 
- A fee payer tries to pay the fee using signature authorization (proofs are not supported). If the zkApp account is used as fee payer after deployment, the transaction will get rejected because the permissions of the account will be violated. This currently breaks all re-deployments …
=> Add Third Party Feepayer 

src/lib/config.js, src/lib/deploy.js, src/lib/example.js, src/lib/file.js, src/lib/project.js, src/lib/prompts.js, src/lib/system.js
This PR includes:
- Minor updates for language
- Changes from the [Slack convo](https://o1-labs.slack.com/archives/C028Q27R8UC/p1687350669404319) making this the suggested command when an earlier version is detected:
`npm install snarkyjs@latest`
=> edits to change SnarkyJS latest install suggestion and other CLI prompt fixes

CONTRIBUTING.md, README.md, package.json
This PR does a few nifty things to improve UX and DX and encourage community contributions:
- creates a contributing file so we can link to it from the What's New in SnarkyJS blog 
- updates README with editorial grooming and adds absolute links that will work on npm (a few busted links on https://www.npmjs.com/package/zkapp-cli, including an examples directory that is someone else's from 9 years ago, oof)
- updates the package.json to help us be more discoverable! 
@ymekuria  it would be cool to include some badges here, like we did for SnarkyJS https://www.npmjs.com/package/snarkyjs
=> UX and DX: create zkApp CLI contributing.md and use absolute links in README so npm works

CHANGELOG.md, package-lock.json, package.json, src/lib/example.js, src/lib/project.js
Closes #506 
This PR removes husky pre-commit hooks configuration steps during project generation with an accompanying UI project. The husky pre-commit hooks were removed from the project templates in this [PR](https://github.com/o1-labs/zkapp-cli/pull/505)
**Tested**
This was tested using the complete end to end testing suite using `npm run e2e:test` .
=> Remove Husky configuration from UI project scaffold generation

CHANGELOG.md, package.json, src/lib/deploy.js, templates/project-ts/src/interact.ts, tests/cli/interact.spec.ts, tests/utils/deploy-utils.ts
We need a way to also respect the network users deploy against (`berkeley`, `testworld`).
Since `MinaExplorer` does not provide the ITN (Testworld) explorer then all links go to `Minascan`.
---
https://minascan.io/berkeley/tx/5JuayhyNyrRUgkUmUvRRqrBk48ZnS4UGBzBzJtN99ruSyi6m8fyu?type=zk-tx
https://minascan.io/testworld/tx/5JuabVWKrCP1a8odXiVVVDNxrRVmEW9FMBGK9dNxYEEcFE4wtjEB?type=zk-tx
=> Change the explorer link to respect different networks.

CHANGELOG.md, package-lock.json, package.json, src/bin/index.js, src/lib/constants.js, src/lib/lightnet.js
- `zk lightnet logs save` command does not provide any selection options, because usually it is good idea to grab all relevant logs at certain point in time.
- `zk lightnet logs follow` command, on the contrary, gives users an option to follow the logs of certain processes, well, because you can't simply follow several files without introducing additional complexity (logs from different sources pre-processing) and a bit of mess when you will also need to distinguish which entries are from what processes.
Closes #502 
---
As per the [RFC](https://github.com/o1-labs/rfcs/blob/522f295075068522f12cadbca46b7788e986f4bf/0010-zkapp-cli-lightnet-management.md).
=> zk lightnet logs command implementation.

CHANGELOG.md, src/bin/index.js, src/lib/constants.js, src/lib/lightnet.js
- Today all the Mina processes are configured to use the `Trace` logging level. This might be too much for certain cases and hence, It will be good to have an ability to change the Mina processes logging level in use.
- Corresponding `lightnet` [images](https://hub.docker.com/r/o1labs/mina-local-network) will be updated with the next build&publishing job.
---
Closes #524
=> [Lightnet] Mina processes logging level configuration exposure.

CHANGELOG.md, update-changelog.sh
This PR formalizes the changelog to be consistent with the [o1js changelog](https://github.com/o1-labs/o1js/blob/main/CHANGELOG.md) by adding branch comparison links for each release version.
closes #540
=> Update Changelog to be consistent with the o1js changelog

src/lib/deploy.js
#550 
#Issue Description
Sometimes deploy script fails to detect the global cli version. it happens if user has installed **Node** via [Volta] (https://volta.sh/) or something similar. In that case `npm list -g --depth 0 --json --silent` doesn't include `zkapp-cli`. 
If that happens, `getInstalledCliVersion` method returns `undefined` and code breaks.
**Changes summary**
To fix this, check the return value of `getInstalledCliVersion` and if is undefined, show a relevant message to user.
=> Handle global cli version detection failure message

README.md
I am working with @shimkiv and he noticed that our docs and this README had the old versions, this PR gets us current
=> fix: update prereq versions for zkApp CLI

templates/project-ts/tsconfig.json
Closes #569 
**Problem**
Invoking  the`SmartContract.compile` method  when `compilerOptions.target` in the `tsconfig` is set to `"ES2022"` or `"ESNext"` causes the following error.
```
Error: get can only be called when the State is assigned to a SmartContract @state.
at Object.get (o1js/dist/node/lib/state.js:135:23)
at Object.getAndRequireEquals (o1js/dist/node/lib/state.js:193:30)
```
See the [issue ](https://github.com/o1-labs/o1js/issues/1380)reported in the o1js repo for more details.
**Solution**
This error was fixed by setting the `useDefineForClassFields` to `false` in the project scaffold `tsconfig`.
**Tested**
This was manualy tested by first reproducing the error, and then setting the `useDefineForClassFields` to `false` in the project scaffold `tsconfig` to …
=> Update project scaffold tsconfig to handle esnext and es2022 targets

CHANGELOG.md, src/lib/deploy.js
Closes #331
This PR improves the error handling for `zk deploy` when the  feepayer has insufficient permissions. A helpful error message is shown to guide a user to use a different feepayer or generate a new one with `zk config`.
=> Feepayer permissions error handling

CHANGELOG.md, src/lib/config.js
Closes #461 
This PR updates the `getCachedFeepayerAliases()` logic to prevent edge case bugs when certain deploy aliases are used.
=> Update cached feepayer logic

CHANGELOG.md, src/lib/deploy.js
Closes #329  
Previously when an error occurred while importing a smart contract from the build directory during the deploy step, the `zkApp CLI` would swallow the error and display the message.
```
Failed to find the "Add" smart contract in your build directory.
Please confirm that your config.json contains the name of the smart contract that you desire to deploy to this deploy alias.
```
There are many different errors that can happen while importing a smart contract. This caused a poor DX, and made it extremely hard for user to find the source of the real errors.
This PR improves the error handling for `zk deploy` when a smart contract is not found in the build directory. A custom error message is only shown to a user if the smart contract is not found in the build directory.  All …
=> Improve error handling when smart contract is not found

CHANGELOG.md, src/bin/index.js
=> Improve CLI errors handling.

CHANGELOG.md, src/lib/system.js
Closes #66 
---
This is odd because `envinfo` issue still exists (when it shows correct data when executed in CLI but fails to find global packages on Windows while invoked via API) despite Windows fixed delivered. 
Fixing it using the `npm` invocation.
=> Address the 'zk system' issue on Windows.

CHANGELOG.md, package-lock.json, package.json, src/lib/project.js, src/lib/ui/next/ghp-postbuild.js, templates/project-ts/package.json
Closes #646 
---
- The `webpack` alias for `o1js` in `next.config.js` is now causing issues. Removing it does not impact `o1js` dependency resolution.
- The `next.config.mjs` is now generated in `ESM`.
- The `next export` is no longer needed since we have the `output: 'export',` in `GH Pages` case. Moreover `next export` now produces error.
- Other UI frameworks work well with updated `o1js` version as well.
=> Migrate to Next.js v14.2.3 and fix latest o1js usage issue.

CHANGELOG.md, package-lock.json, package.json, src/lib/helpers.js
=> Fix for the deployment procedure of zkApps that use `o1js` of version < `v1.0.1` and that use local imports without the `.js` extension.

tests/pages/example/LandingPage.ts
Closes #559 (upgrading to the `Next.js v14+` fixed the issue)
Closes #655
=> Fix for E2E tests after migration to Next.js v14+

src/lib/constants.js, src/lib/lightnet.js, tests/mocks/mocked-endpoints.ts, tests/ui/ui.spec.ts, tests/utils/network-utils.ts
Sometimes, while switching between the NodeJS versions, it was noticed that `localhost` can be resolved to IPv6 address and fails the Lightnet communications.
Possibly related to: https://github.com/nodejs/node/issues/40702
=> Explicitly use IPv4 comms since 'localhost' can be resolved differently.

.eslintignore, .npmignore, CHANGELOG.md, package-lock.json, package.json, src/lib/example.js, src/lib/helpers.js, src/lib/project.js, templates/project-ts/_.gitignore, templates/project-ts/_.npmignore, tests/utils/common-utils.ts, tests/utils/example-utils.ts, tests/utils/project-utils.ts
Closes #615
E2E testing results: https://github.com/o1-labs/zkapp-cli/actions/runs/9331728280
---
- The NPM package content has been improved (you can check it locally with the `npm pack` and compare with the [currently published one](https://www.npmjs.com/package/zkapp-cli?activeTab=code)).
- We now use `templates` and `examples` from file system of installed application.
- We no longer depend on `gittat` dependency (which also has some vulnerabilities as of time of writing).
- We had to rename `templates/project-ts/.gitignore` and `templates/project-ts/.npmignore` by adding the `_` prefix because these configs were recursively applied upon the publishing to NPM and there is no other way to skip their application except of having them with wrong names but rename them once …
=> Change the way sources are fetched during the project generation.

templates/project-ts/jest.config.js, templates/project-ts/package.json
Closes #672
This PR updates typescript version of template project to match with ts version of o1js. Jest and ts-jest are updated to typescript v5 compatible versions.
=> chore(package.json): update template typescript, jest and ts-jest versions

CHANGELOG.md, src/lib/deploy.js, src/lib/deploy.test.js
=> Fix zkProgramFile to support nested paths

CHANGELOG.md, src/lib/project.js
Thanks to @anarkrypto on this issue https://github.com/o1-labs/o1js/issues/1811 !  This added config fixes the `Error: ENOENT: no such file or directory, open '.../.../.next/server/vendor-chunks/plonk_wasm_bg.wasm` issue in next js server
=> Mark o1js as an external dependency for next JS server config

.gitignore, CHANGELOG.md, package.json, src/bin/index.js, src/lib/project.js, src/lib/project.test.js, src/lib/ui/next/components/GradientBG.js, src/lib/ui/next/customNextLayout.js, src/lib/ui/next/customNextPage.js, src/lib/ui/next/styles/globals.css, src/lib/ui/nuxt/customNuxtIndex.js, src/lib/ui/svelte/customPageSvelte.js
Updates the project starter to use the latest version of Nextjs with app router and no src directory. Removes the js project option. Closes
https://github.com/o1-labs/zkapp-cli/issues/583
https://github.com/o1-labs/zkapp-cli/issues/400
=> Update nextjs project starter to use TS + App Router

CHANGELOG.md, package-lock.json, package.json, src/lib/project.js, src/lib/project.test.js, src/lib/ui/svelte/customLayoutSvelte.js, src/lib/ui/svelte/gradientBackground.js, tests/utils/project-utils.ts
=> Support for the Svelte 5 env.

package-lock.json, package.json, templates/project-ts/package.json
This PR releases version `0.22.0` of the `zkapp-CLI` which coincides with [release](https://github.com/o1-labs/o1js/pull/1873) version `2.0.0` of `o1js`.
The `o1js` major version dependency in the CLI `package.json` was updated to  `^2.*`. The o1js major version peer dependency was updated in `template/example` contracts `package.json `to `^2.*`. 
The updates introduced in this PR have been tested with the full e2e suite.
=> Release v22.0

CHANGELOG.md, CONTRIBUTING.md, package-lock.json, package.json, src/lib/ui/next/customNextPage.js
- Fixes issues introduced by https://github.com/o1-labs/zkapp-cli/pull/709
- `package-lock` file update;
- Next.js project without GH Pages enabled (duplicated and redundant import).
- Dependencies vulnerabilities fix (audit).
- Version bump to re-release the app.
=> Fix e2e tests and lock file, deps audit.
