o1-labs/zkapp-cli

package-lock.json, package.json, src/lib/file.test.js
Fixes https://github.com/o1-labs/snapp-cli/issues/64
=> [Windows] - Fix Jest tests

.npmignore, templates/project-ts/.npmignore, templates/project-ts/package.json, templates/project-ts/tsconfig.json
Configures project-ts so that devs can push it to NPM easily
=> feat: configure project builds for npm

README.md, package.json, src/bin/index.js, src/lib/example.js, src/lib/project.js, src/lib/project.test.js, templates/project-ts/README.md
=> Use proper casing for Mina and snapps

examples/tictactoe/ts/src/index.ts
the example doesn't run without this.
=> added isReady to tic-tac-toe example

examples/sudoku/js/src/index.js, examples/sudoku/ts/src/index.test.ts, examples/sudoku/ts/src/index.ts, examples/sudoku/ts/src/sudoku-lib.js, examples/sudoku/ts/src/sudoku-snapp.ts, templates/project-ts/package.json, templates/project-ts/tsconfig.json
Add sudoku example, plus some small changes / fixes to the template project
- fix tsconfig - module: es2022, so examples can use top-level await - remove importHelpers because that needs "tslib" as runtime dependency
- fix: make snarkyjs a runtime dependency
- add sudoku example
- fix sudoku example
- add jest test
=> Add sudoku example

examples/sudoku/ts/src/index.test.ts, examples/sudoku/ts/src/index.ts, examples/sudoku/ts/src/sudoku-snapp.ts, examples/tictactoe/ts/src/index.ts, package-lock.json, package.json, templates/project-ts/package-lock.json, templates/project-ts/package.json, templates/project-ts/src/index.ts
Bump snarkyjs to 0.2 and update both examples to match the new API
=> SnarkyJS 0.2

src/bin/index.js, src/lib/config.js
Ready to go, except we're blocked on key pair generation. Leaving commented out until it's fully usable.
=> feat: add config command

examples/sudoku/ts/src/index.ts, examples/sudoku/ts/src/sudoku-snapp.ts, templates/project-ts/src/index.ts
=> Fix example

src/bin/index.js
fixes https://github.com/o1-labs/zkapp-cli/issues/171
=> fix: make unknown command red

src/lib/config.js
Addresses: https://github.com/o1-labs/zkapp-cli/issues/182
=> feat: update config helper text to describe Mina GraphQL API URL

examples/tictactoe/ts/src/index.ts, examples/tictactoe/ts/src/tictactoe.ts, package-lock.json, package.json
This fixes #186
Updates the `TicTacToe` example to deploy successfully on the Berkeley network. This was done by splitting up the example into 2 separate files, one being `index.ts` and the other being `tictactoe.ts`
`index.ts` holds the smart contract definition and the other related classes it needs to be functional and deployed. 
`tictactoe.ts` holds the logic to run the smart contract locally. This was previously stuffed into `index.ts` and was being run when deploying. We move all the logic to run the smart contract locally in it's own file to separate concerns. 
**Note**: This means that to run the smart contract locally, users will need to run `npm run build && node build/src/tictactoe.js` instead of specifying `build/src/index.js`
**Tested**
Deployed to Berkeley on …
=> Update TicTacToe example to deploy to Berkeley

package-lock.json, package.json, src/bin/index.js, src/lib/deploy.js
Tested by creating a project and deploying to QANet.
=> feat: rename deploy param from network to alias

package-lock.json, package.json, src/lib/deploy.js, templates/project-ts/package-lock.json, templates/project-ts/package.json
- bump snarkyjs
- reduce the time estimate for "Generate verification key" during deploy
=> Snarkyjs 0.4.3

package-lock.json, package.json, src/lib/deploy.js
This modifies the deploy transaction, to comply with the new rules in the transaction pool logic: https://github.com/MinaProtocol/mina/pull/11631
=> Remove nonce increment by non-fee-payer

src/lib/deploy.js, templates/project-ts/package.json
1. Fixed the problem that "zk deploy" executes incorrectly under windows.
2. Make the test commands in the project template work on various platforms.
fixes https://github.com/o1-labs/zkapp-cli/issues/254
=> fix problems running under windows

package-lock.json, package.json
=> bump version to 0.4.17

templates/project-ts/package.json
=> Set default verion of user's smart contract project to 0.1.0

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Includes 1.) Bug report, 2.) Feature request, 3.) Discord link to #zkapps-developers on Mina Protocol's discord.
Lmk what you think @bkase. We can iterate on these. When they look good to others, I'll PR for the SnarkyJS repo too.
=> feat: add Github issue templates 

src/lib/project.js
=> Add dependencies object to package json if none is found in UI CLI scaffolds

src/lib/project.js
=> Update text prompt for Github Pages

src/lib/project.js, templates/project-ts/package.json
Closes #308 
This PR adds a tsc watch script to the contract package.json.
=> Add tsc watch script to contract package.json

examples/sudoku/ts/src/run.ts, examples/sudoku/ts/src/sudoku.test.ts, examples/tictactoe/ts/src/run.ts, examples/tictactoe/ts/src/tictactoe.test.ts, package-lock.json, package.json, src/postinstall.js, templates/project-ts/package-lock.json, templates/project-ts/package.json
Closes #366 
This PR updates the `zkApp-cli` and all the template/example contracts to be compatible with `SnarkyJS 0.90`. 
**Tested**
The template `Add` smart contract was successfully [deployed.](https://berkeley.minaexplorer.com/transaction/5Jta9coNhYKeHuF7kYhPuL1XyEKDtM62D3YFAGE9N37o3EFU13xM) . Example contracts were generated from the `zkApp-cli` and confirmed that tests and run scripts ran correctly.
=> Release 0.7.0 -  Update SnarkyJS version to 0.9.0  

examples/sudoku/ts/src/run.ts, examples/sudoku/ts/src/sudoku.test.ts, examples/tictactoe/ts/src/run.ts, examples/tictactoe/ts/src/tictactoe.test.ts, package-lock.json, package.json, templates/project-ts/package-lock.json, templates/project-ts/package.json
=> Update for snarkyjs state getting fix

templates/project-ts/src/interact.ts
Very small correction to the template config field
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204474238279928
=> Update config field

.eslintignore, .github/workflows/e2e-test-ci.yml, .gitignore, .husky/pre-commit, .nvmrc, .prettierignore, README.md, package-lock.json, package.json, playwright.config.ts, tests/build-helper.mjs, tests/cli/common/command.spec.ts
- Project configuration for the e2e testing using `Playwright` (we will need one for UI testing), `@gmrchk/cli-testing-library` and `execa` for interactive CLI application interaction;
- Added separate GitHub Actions workflow for e2e tests;
- Pre-commit hook update in order to execute `linter` and `prettier`;
- New `package.json` scripts and dependencies;
- Initial example test added and more to come!
=> E2E tests init and improvements

CHANGELOG.md
Closes #419 
This PR updates the changelog  from version `0.6.2 to 0.8.2`.
=> Update Changelog version 0.8.2 to 0.6.2

src/lib/project.js
=> add build target to svelte config

CHANGELOG.md, package.json, src/lib/project.js, src/lib/ui/next/customNextIndex.js
=> Fix for Nuxt projects and NextJS getting stated page text.

README.md
to make sure our users know how zkApp CLI updates are prompted, this PR adds the context and update instructions.
=> README add update instructions

CHANGELOG.md, package-lock.json, package.json, src/lib/deploy.js, templates/project-ts/package.json
Closes #457 
This PR is the corresponding zkApp cli release to the SnarkyJS release https://github.com/o1-labs/snarkyjs/pull/1021.
- SnarkyJS minor version dependency updated in cli package.json to 0.12.*.
- SnarkyJS minor version peer dependency updated in template/example contract package.json to 0.12.*.
Tested
This was tested by generating projects with various cli flows. The template [add]( https://berkeley.minaexplorer.com/transaction/5JuLuyGfTwceZyyoRSVDcvADLiCttgJpqip6yGsLJqu984q71tPn) contract, [sudoku](https://berkeley.minaexplorer.com/transaction/5JuXziEtHrXVdaqsyTwdmEWHK6MGwW8pR1KqL7Cvvei5yDV1adt5), and [tictactoe](https://berkeley.minaexplorer.com/transaction/5Jv1JSAXk5GFZYz3hFiUs1Q9gxAvWHWFJD9hua6aduJTKDkA8Qya) examples were all successfully deployed.
=> CLI Release 0.11.0

.github/workflows/ci.yml, .github/workflows/e2e-test-ci.yml, README.md, templates/project-ts/package.json
=> Node 20 support. Remove --experimental-wasm-threads CLI option.

.github/workflows/nightly-e2e-ci-tests.yml, .github/workflows/smoke-e2e-ci-tests.yml, src/lib/deploy.js
=> Roll back to default Node v20+

CONTRIBUTING.md
This PR include consistency edits to the zkApp CLI contributing file
=> zkApp CLI: CONTRIBUTING.md

.github/actions/e2e-shared/action.yml, .github/workflows/ci.yml, .github/workflows/nightly-e2e-ci-tests.yml, .github/workflows/smoke-e2e-ci-tests.yml, src/bin/index.js, src/lib/constants.js, templates/project-ts/.github/workflows/ci.yml
- And CI actions versions bump.
=> Rename Mina's rampup branch to o1js-main.

src/bin/index.js, src/lib/lightnet.js
=> Add links to Lightnet usage public docs.

README.md
I was too quick to merge a previous PR and missed a few suggestions from @shimkiv  
This PR fixes that error
Thank you, as always, @shimkiv  for your high quality work and ALWAYS making things better
=> fix: update README with link to contributing and add --help

CHANGELOG.md, package-lock.json, package.json
This PR bumps the minor version of the zkApp-CLI.
=> Release 0.17.0

src/lib/prompts.js, tests/cli/config.spec.ts
Closes #421
Closes #428 
Closes #462 
Closes #463 
Closes #475
=> `zk config` validation.

CHANGELOG.md, package-lock.json, package.json, templates/project-ts/package.json
Accompanying PR to https://github.com/o1-labs/o1js/pull/1442
=> Upgrade deps and bump version.

CHANGELOG.md, package-lock.json, package.json, templates/project-ts/package.json, templates/project-ts/src/interact.ts, tests/cli/config.spec.ts, tests/ui/ui.spec.ts, tests/utils/cli-utils.ts
Closes #588 
Closes #558 
---
Fixes tests.
=> Cumulative updates and fixes.

src/lib/ui/svelte/customPageSvelte.js
https://github.com/o1-labs/o1js/pull/1515
=> Reflect o1js deprecations removal.

.github/workflows/ci.yml
- Similar to https://github.com/o1-labs/o1js/pull/1596
- [Internal discussion](https://o1-labs.slack.com/archives/C028Q27R8UC/p1713444295203599).
=> Trigger artifacts release jobs only on merge into 'main'.

src/lib/config.js, src/lib/deploy.js
=> Extend information printed during deployment procedure & fix for Faucet URL.

src/lib/deploy.js, templates/project-ts/src/interact.ts
Corresponds to changes in docs: https://github.com/o1-labs/docs2/pull/927
---
Services links provided by `Minascan` were discussed with `Staketab` representative in Discord (`@duccaofficial`).
=> Update txns link to Minascan.

CHANGELOG.md, package-lock.json, package.json, src/lib/deploy.js
Closes #635 
---
Actual solution will take more efforts: https://github.com/o1-labs/zkapp-cli/issues/636
=> Search for class names that extend any other classes (hotfix).

tests/utils/deploy-utils.ts
Related to https://github.com/o1-labs/zkapp-cli/pull/637
=> Fix nightly e2e tests after the classes lookup hotfix delivery.

package-lock.json
🤦 
cc https://github.com/o1-labs/zkapp-cli/pull/641/files
=> Fix package-lock.json after engines version bump.

package-lock.json, package.json, templates/project-ts/package.json
Since we updated TypeScript version in o1js, we need to update the TypeScript version in our template
Currently, we get the following error output:
```sh
✔ UI: Set up project
- Initialize Git repo...
✔ Initialize Git repo
- Set up project...
✔ Set up project
- NPM install...
✔ NPM install
- NPM build contract...
Error: node_modules/o1js/dist/node/lib/mina/actions/offchain-state.d.ts(99,32): error TS1139: Type parameter declaration expected.
Error: node_modules/o1js/dist/node/lib/mina/actions/offchain-state.d.ts(99,45): error TS1005: ',' expected.
Error: node_modules/o1js/dist/node/lib/mina/actions/offchain-state.d.ts(100,9): error TS1005: ']' expected.
Error: node_modules/o1js/dist/node/lib/mina/actions/offchain-state.d.ts(100,17): error TS1005: ',' expected.
Error: …
```
=> chore(package.json): update jest, ts-jest, and typescript versions

package-lock.json, package.json, src/lib/constants.js, src/lib/helpers.js
> Remove 'o1js-main' branch from available options
[Internal](https://o1-labs.slack.com/archives/C028Q27R8UC/p1715970755154459).
> Relax sources parser rules
[Discord](https://discord.com/channels/484437221055922177/915745847692636181/1241027312309502022).
=> Remove 'o1js-main' branch from available options and relax sources parser rules.

tests/ui/ui.spec.ts
Missed part of https://github.com/o1-labs/zkapp-cli/pull/658
=> Explicitly use IPv4 comms since 'localhost' can be resolved differently (e2e tests).

.github/workflows/pkg-pr-new-publish.yml, package-lock.json, package.json
Closes #673.
---
[Internal discussion](https://o1-labs.slack.com/archives/C028Q27R8UC/p1719501385494779).
=> Continuous releases on pkg-pr-new.

src/lib/deploy.js, src/lib/helpers.js
=> Fix for the SmartContract lookup.

src/lib/lightnet.js
=> Prioritise IPv4 over IPv6 for DNS resolution and add more debug logs to track the network readiness checking issues.
